### ISSUE TITLE
Where's the book?

### ISSUE THREAD

**Issue by wkjung** [PacktPublishing/Demystified-Object-Oriented-Programming-with-CPP#1]
The purchase link in the readme [you posted](https://www.packtpub.com/product/demystified-object-oriented-programming-with-c/9781839218835?utm_source=github&utm_medium=repository&utm_campaign=9781839218835) seems to be wrong. Where's the corresponding book that I can buy?

**Comment by gaurav-packt** [comment]
Hello, this book is currently off the market for purchase. We'll share an update on the website as soon as the book is due for purchase.
